# Generated by Django 5.2.4 on 2025-10-28 15:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMercancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Mercancía',
                'verbose_name_plural': 'Categorías de Mercancías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo', models.CharField(choices=[('PERSONA', 'Persona Natural'), ('EMPRESA', 'Empresa'), ('COOPERATIVA', 'Cooperativa'), ('ESTATAL', 'Entidad Estatal')], default='EMPRESA', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('identificacion', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('licencia_sanitaria', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_vencimiento_licencia', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('calificacion', models.IntegerField(default=5, help_text='Calificación del proveedor (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mercancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('peso_unitario', models.DecimalField(blank=True, decimal_places=3, help_text='Peso unitario en kg', max_digits=10, null=True)),
                ('volumen_unitario', models.DecimalField(blank=True, decimal_places=3, help_text='Volumen unitario en litros', max_digits=10, null=True)),
                ('stock_actual', models.DecimalField(decimal_places=3, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('requiere_vencimiento', models.BooleanField(default=False, help_text='Si la mercancia tiene fecha de vencimiento')),
                ('requiere_lote', models.BooleanField(default=False, help_text='Si la mercancia requiere control por lotes')),
                ('dias_vida_util', models.IntegerField(blank=True, help_text='Días de vida útil desde la fecha de producción', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('temperatura_almacenamiento', models.CharField(choices=[('AMBIENTE', 'Temperatura Ambiente'), ('REFRIGERADO', 'Refrigerado (2-8°C)'), ('CONGELADO', 'Congelado (-18°C)'), ('SECO', 'Lugar Seco')], default='AMBIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('visible_venta', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mercancias', to='mercancia.categoriamercancia')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mercancias_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mercancía',
                'verbose_name_plural': 'Mercancías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='LoteMercancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=100)),
                ('fecha_produccion', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('cantidad_inicial', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad_actual', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado_calidad', models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('VENCIDO', 'Vencido'), ('DAÑADO', 'Dañado'), ('CUARENTENA', 'En Cuarentena')], default='BUENO', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('mercancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='mercancia.mercancia')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_mercancias', to='mercancia.proveedor')),
            ],
            options={
                'verbose_name': 'Lote de Mercancia',
                'verbose_name_plural': 'Lotes de Mercancias',
                'ordering': ['-fecha_produccion'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE_POSITIVO', 'Ajuste Positivo'), ('AJUSTE_NEGATIVO', 'Ajuste Negativo'), ('TRANSFERENCIA_ENTRADA', 'Transferencia Entrada'), ('TRANSFERENCIA_SALIDA', 'Transferencia Salida'), ('MERMA', 'Merma'), ('VENCIMIENTO', 'Por Vencimiento')], max_length=25)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_anterior', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_posterior', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_movimiento', models.DateTimeField(default=django.utils.timezone.now)),
                ('razon', models.CharField(blank=True, max_length=200, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('documento_referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_mercancia_creados', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_mercancias', to='mercancia.lotemercancia')),
                ('mercancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_mercancias_stock', to='mercancia.mercancia')),
                ('usuario_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_mercancia_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.AddIndex(
            model_name='mercancia',
            index=models.Index(fields=['codigo'], name='mercancia_m_codigo_2f84d5_idx'),
        ),
        migrations.AddIndex(
            model_name='mercancia',
            index=models.Index(fields=['categoria', 'activo'], name='mercancia_m_categor_6763a7_idx'),
        ),
        migrations.AddIndex(
            model_name='mercancia',
            index=models.Index(fields=['stock_actual'], name='mercancia_m_stock_a_4a6e88_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['mercancia', 'fecha_movimiento'], name='mercancia_m_mercanc_6bc144_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['tipo_movimiento'], name='mercancia_m_tipo_mo_fce814_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['fecha_movimiento'], name='mercancia_m_fecha_m_8ac226_idx'),
        ),
        migrations.AddIndex(
            model_name='lotemercancia',
            index=models.Index(fields=['numero_lote'], name='mercancia_l_numero__f310a6_idx'),
        ),
        migrations.AddIndex(
            model_name='lotemercancia',
            index=models.Index(fields=['fecha_vencimiento'], name='mercancia_l_fecha_v_26266d_idx'),
        ),
        migrations.AddIndex(
            model_name='lotemercancia',
            index=models.Index(fields=['estado_calidad'], name='mercancia_l_estado__6483bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lotemercancia',
            unique_together={('mercancia', 'numero_lote')},
        ),
    ]
