# Generated by Django 5.2.4 on 2025-11-04 17:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_cliente_codigo'),
        ('mercancia', '0002_alter_mercancia_codigo_alter_proveedor_codigo'),
        ('productos', '0005_alter_producto_codigo_alter_proveedor_codigo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha_venta', models.DateTimeField(default=django.utils.timezone.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='clientes.cliente')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_lote', to='productos.loteproducto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_producto', to='productos.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_productos', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta - Producto',
                'verbose_name_plural': 'Detalles de Venta - Productos',
            },
        ),
        migrations.CreateModel(
            name='DetalleVentaMercancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_lote', to='mercancia.lotemercancia')),
                ('mercancia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_mercancia', to='mercancia.mercancia')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_mercancias', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta - Mercancía',
                'verbose_name_plural': 'Detalles de Venta - Mercancías',
            },
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['fecha_venta'], name='ventas_vent_fecha_v_357f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['cliente', 'estado'], name='ventas_vent_cliente_546058_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['codigo'], name='ventas_vent_codigo_fb2c3f_idx'),
        ),
        migrations.AddIndex(
            model_name='detalleventaproducto',
            index=models.Index(fields=['venta', 'producto'], name='ventas_deta_venta_i_6fefa2_idx'),
        ),
        migrations.AddIndex(
            model_name='detalleventaproducto',
            index=models.Index(fields=['lote'], name='ventas_deta_lote_id_87cd67_idx'),
        ),
        migrations.AddIndex(
            model_name='detalleventamercancia',
            index=models.Index(fields=['venta', 'mercancia'], name='ventas_deta_venta_i_05092d_idx'),
        ),
        migrations.AddIndex(
            model_name='detalleventamercancia',
            index=models.Index(fields=['lote'], name='ventas_deta_lote_id_dadc21_idx'),
        ),
    ]
