# Generated by Django 5.2.4 on 2025-10-30 03:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicaAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('icono', models.CharField(blank=True, help_text='Clase de icono FontAwesome', max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Característica Adicional',
                'verbose_name_plural': 'Características Adicionales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Inmueble',
                'verbose_name_plural': 'Tipos de Inmuebles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del inmueble', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre o identificación del inmueble', max_length=200)),
                ('area_total', models.DecimalField(decimal_places=2, help_text='Área total en metros cuadrados', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('area_util', models.DecimalField(blank=True, decimal_places=2, help_text='Área útil en metros cuadrados', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('altura', models.DecimalField(blank=True, decimal_places=2, help_text='Altura en metros', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('capacidad_carga', models.DecimalField(blank=True, decimal_places=2, help_text='Capacidad de carga en toneladas', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('numero_ambientes', models.IntegerField(default=1, help_text='Número de ambientes o divisiones', validators=[django.core.validators.MinValueValidator(0)])),
                ('numero_banos', models.IntegerField(default=0, help_text='Número de baños', validators=[django.core.validators.MinValueValidator(0)])),
                ('numero_estacionamientos', models.IntegerField(default=0, help_text='Número de estacionamientos', validators=[django.core.validators.MinValueValidator(0)])),
                ('direccion', models.TextField(help_text='Dirección completa')),
                ('ciudad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('coordenadas_lat', models.DecimalField(blank=True, decimal_places=7, help_text='Latitud', max_digits=10, null=True)),
                ('coordenadas_lng', models.DecimalField(blank=True, decimal_places=7, help_text='Longitud', max_digits=10, null=True)),
                ('tipo_uso', models.CharField(choices=[('ALMACENAMIENTO', 'Almacenamiento'), ('REFRIGERACION', 'Refrigeración'), ('CONGELACION', 'Congelación'), ('OFICINA', 'Oficina'), ('MIXTO', 'Uso Mixto')], default='ALMACENAMIENTO', max_length=20)),
                ('condicion', models.CharField(choices=[('EXCELENTE', 'Excelente'), ('BUENA', 'Buena'), ('REGULAR', 'Regular'), ('REQUIERE_REPARACION', 'Requiere Reparación')], default='BUENA', max_length=30)),
                ('ano_construccion', models.IntegerField(blank=True, help_text='Año de construcción', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('tiene_electricidad', models.BooleanField(default=True)),
                ('tiene_agua', models.BooleanField(default=True)),
                ('tiene_gas', models.BooleanField(default=False)),
                ('tiene_internet', models.BooleanField(default=False)),
                ('tiene_seguridad', models.BooleanField(default=False)),
                ('tiene_vigilancia_24h', models.BooleanField(default=False)),
                ('tiene_camaras', models.BooleanField(default=False)),
                ('tiene_alarma', models.BooleanField(default=False)),
                ('tiene_extintor', models.BooleanField(default=False)),
                ('tiene_rociadores', models.BooleanField(default=False)),
                ('tiene_carga_descarga', models.BooleanField(default=False)),
                ('tiene_montacargas', models.BooleanField(default=False)),
                ('tiene_rampa', models.BooleanField(default=False)),
                ('precio_arriendo_mensual', models.DecimalField(decimal_places=2, help_text='Precio de arriendo mensual', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('gastos_comunes', models.DecimalField(decimal_places=2, default=0, help_text='Gastos comunes mensuales', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('deposito_garantia', models.DecimalField(blank=True, decimal_places=2, help_text='Depósito de garantía requerido', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('dias_preaviso', models.IntegerField(default=30, help_text='Días de preaviso para desocupar', validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ARRENDADO', 'Arrendado'), ('MANTENIMIENTO', 'En Mantenimiento'), ('RESERVADO', 'Reservado'), ('NO_DISPONIBLE', 'No Disponible')], default='DISPONIBLE', max_length=20)),
                ('fecha_disponibilidad', models.DateField(blank=True, help_text='Fecha desde la cual está disponible', null=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del inmueble', null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones internas', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False, help_text='Marcar como destacado en listados')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inmuebles_creados', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inmuebles', to='inmuebles.tipoinmueble')),
            ],
            options={
                'verbose_name': 'Inmueble',
                'verbose_name_plural': 'Inmuebles',
                'ordering': ['-destacado', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ImagenInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Imagen del inmueble', upload_to='inmuebles/%Y/%m/')),
                ('titulo', models.CharField(blank=True, help_text='Título o descripción de la imagen', max_length=200, null=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='inmuebles.inmueble')),
            ],
            options={
                'verbose_name': 'Imagen de Inmueble',
                'verbose_name_plural': 'Imágenes de Inmuebles',
                'ordering': ['-es_principal', 'orden', 'fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='MantenimientoInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo'), ('EMERGENCIA', 'Emergencia')], max_length=20)),
                ('descripcion', models.TextField(help_text='Descripción del mantenimiento')),
                ('fecha_programada', models.DateField(help_text='Fecha programada para el mantenimiento')),
                ('fecha_realizacion', models.DateField(blank=True, help_text='Fecha en que se realizó el mantenimiento', null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, help_text='Costo del mantenimiento', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('proveedor', models.CharField(blank=True, help_text='Proveedor que realizó el mantenimiento', max_length=200, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_creados', to=settings.AUTH_USER_MODEL)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='inmuebles.inmueble')),
            ],
            options={
                'verbose_name': 'Mantenimiento de Inmueble',
                'verbose_name_plural': 'Mantenimientos de Inmuebles',
                'ordering': ['-fecha_programada'],
            },
        ),
        migrations.CreateModel(
            name='InmuebleCaracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(blank=True, help_text='Valor específico de la característica (opcional)', max_length=200, null=True)),
                ('caracteristica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmuebles.caracteristicaadicional')),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas_adicionales', to='inmuebles.inmueble')),
            ],
            options={
                'verbose_name': 'Característica del Inmueble',
                'verbose_name_plural': 'Características de Inmuebles',
                'unique_together': {('inmueble', 'caracteristica')},
            },
        ),
        migrations.AddIndex(
            model_name='inmueble',
            index=models.Index(fields=['codigo'], name='inmuebles_i_codigo_9c430c_idx'),
        ),
        migrations.AddIndex(
            model_name='inmueble',
            index=models.Index(fields=['estado', 'activo'], name='inmuebles_i_estado_79498b_idx'),
        ),
        migrations.AddIndex(
            model_name='inmueble',
            index=models.Index(fields=['tipo', 'ciudad'], name='inmuebles_i_tipo_id_bffc1f_idx'),
        ),
        migrations.AddIndex(
            model_name='inmueble',
            index=models.Index(fields=['precio_arriendo_mensual'], name='inmuebles_i_precio__b0cb04_idx'),
        ),
    ]
