# Generated by Django 5.2.4 on 2025-10-23 15:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cedula', models.CharField(blank=True, help_text='Número de cédula de identidad (11 dígitos)', max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe tener 11 dígitos', regex='^\\d{11}$')])),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono de contacto', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Número de teléfono válido', regex='^\\+?1?\\d{8,15}$')])),
                ('direccion', models.TextField(blank=True, help_text='Dirección de residencia', max_length=500, null=True)),
                ('cargo', models.CharField(blank=True, help_text='Cargo o posición en la empresa', max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, choices=[('ADMINISTRACION', 'Administración'), ('INVENTARIO', 'Inventario'), ('ALMACEN', 'Almacén'), ('VENTAS', 'Ventas'), ('COMPRAS', 'Compras'), ('CONTABILIDAD', 'Contabilidad'), ('RECURSOS_HUMANOS', 'Recursos Humanos'), ('SISTEMAS', 'Sistemas')], help_text='Departamento al que pertenece', max_length=100, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, help_text='Fecha de ingreso a la empresa', null=True)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, help_text='Salario mensual', max_digits=10, null=True)),
                ('avatar', models.ImageField(blank=True, help_text='Foto de perfil del usuario', null=True, upload_to='avatars/')),
                ('intentos_fallidos', models.PositiveIntegerField(default=0, help_text='Número de intentos de login fallidos consecutivos')),
                ('bloqueado_hasta', models.DateTimeField(blank=True, help_text='Fecha hasta la cual el usuario está bloqueado', null=True)),
                ('ultimo_cambio_password', models.DateTimeField(blank=True, help_text='Fecha del último cambio de contraseña', null=True)),
                ('requiere_cambio_password', models.BooleanField(default=False, help_text='Si el usuario debe cambiar su contraseña en el próximo login')),
                ('tema_preferido', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('auto', 'Automático')], default='light', help_text='Tema visual preferido', max_length=20)),
                ('idioma_preferido', models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', help_text='Idioma preferido', max_length=10)),
                ('notificaciones_email', models.BooleanField(default=True, help_text='Recibir notificaciones por email')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ip_ultima_conexion', models.GenericIPAddressField(blank=True, help_text='IP de la última conexión', null=True)),
                ('navegador_ultima_conexion', models.CharField(blank=True, help_text='Navegador usado en la última conexión', max_length=200, null=True)),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_creados', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['username'],
                'permissions': [('can_view_all_users', 'Puede ver todos los usuarios'), ('can_manage_user_permissions', 'Puede gestionar permisos de usuarios'), ('can_reset_passwords', 'Puede resetear contraseñas'), ('can_block_users', 'Puede bloquear/desbloquear usuarios'), ('can_view_audit_logs', 'Puede ver logs de auditoría')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biografia', models.TextField(blank=True, help_text='Biografía o descripción profesional', max_length=1000, null=True)),
                ('especialidades', models.CharField(blank=True, help_text='Especialidades o áreas de expertise (separadas por comas)', max_length=500, null=True)),
                ('certificaciones', models.TextField(blank=True, help_text='Certificaciones profesionales', max_length=1000, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.CharField(blank=True, max_length=50, null=True)),
                ('mostrar_email_publico', models.BooleanField(default=False, help_text='Mostrar email en perfil público')),
                ('mostrar_telefono_publico', models.BooleanField(default=False, help_text='Mostrar teléfono en perfil público')),
                ('perfil_publico', models.BooleanField(default=False, help_text='Hacer el perfil visible públicamente')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='SesionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Usuario',
                'verbose_name_plural': 'Sesiones de Usuario',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('VIEW', 'Visualización'), ('EXPORT', 'Exportación'), ('IMPORT', 'Importación'), ('PASSWORD_CHANGE', 'Cambio de contraseña'), ('PASSWORD_RESET', 'Reset de contraseña'), ('PERMISSION_CHANGE', 'Cambio de permisos'), ('BLOCK', 'Bloqueo de usuario'), ('UNBLOCK', 'Desbloqueo de usuario')], max_length=20)),
                ('modelo_afectado', models.CharField(blank=True, help_text='Nombre del modelo afectado', max_length=100, null=True)),
                ('objeto_id', models.CharField(blank=True, help_text='ID del objeto afectado', max_length=100, null=True)),
                ('descripcion', models.TextField(help_text='Descripción detallada de la acción')),
                ('datos_anteriores', models.JSONField(blank=True, help_text='Datos antes del cambio (JSON)', null=True)),
                ('datos_nuevos', models.JSONField(blank=True, help_text='Datos después del cambio (JSON)', null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('url_solicitada', models.CharField(blank=True, max_length=500, null=True)),
                ('metodo_http', models.CharField(blank=True, max_length=10, null=True)),
                ('codigo_respuesta', models.IntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'accion'], name='usuarios_lo_usuario_13e526_idx'), models.Index(fields=['fecha_creacion'], name='usuarios_lo_fecha_c_67c47b_idx'), models.Index(fields=['modelo_afectado', 'objeto_id'], name='usuarios_lo_modelo__db8868_idx')],
            },
        ),
    ]
