# Generated by Django 5.2.4 on 2025-10-30 03:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inmuebles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoArrendatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Arrendatario',
                'verbose_name_plural': 'Tipos de Arrendatarios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Arrendatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del arrendatario', max_length=20, unique=True)),
                ('tipo_persona', models.CharField(choices=[('NATURAL', 'Persona Natural'), ('JURIDICA', 'Persona Jurídica')], default='NATURAL', max_length=20)),
                ('nombres', models.CharField(blank=True, help_text='Nombres completos (para persona natural)', max_length=200, null=True)),
                ('apellidos', models.CharField(blank=True, help_text='Apellidos completos (para persona natural)', max_length=200, null=True)),
                ('razon_social', models.CharField(blank=True, help_text='Razón social (para persona jurídica)', max_length=200, null=True)),
                ('nombre_comercial', models.CharField(blank=True, help_text='Nombre comercial', max_length=200, null=True)),
                ('identificacion', models.CharField(help_text='Número de identificación (cédula, RUC, pasaporte, etc.)', max_length=50, unique=True)),
                ('telefono_principal', models.CharField(max_length=20)),
                ('telefono_secundario', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('email_secundario', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(help_text='Dirección de domicilio o fiscal')),
                ('ciudad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('pais', models.CharField(default='Ecuador', max_length=100)),
                ('ocupacion', models.CharField(blank=True, help_text='Ocupación o actividad económica', max_length=200, null=True)),
                ('lugar_trabajo', models.CharField(blank=True, help_text='Lugar de trabajo o empresa', max_length=200, null=True)),
                ('telefono_trabajo', models.CharField(blank=True, max_length=20, null=True)),
                ('ingresos_mensuales', models.DecimalField(blank=True, decimal_places=2, help_text='Ingresos mensuales aproximados', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('referencia_nombre', models.CharField(blank=True, help_text='Nombre de referencia personal', max_length=200, null=True)),
                ('referencia_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('referencia_relacion', models.CharField(blank=True, help_text='Relación con la referencia', max_length=100, null=True)),
                ('emergencia_nombre', models.CharField(blank=True, help_text='Nombre del contacto de emergencia', max_length=200, null=True)),
                ('emergencia_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('emergencia_relacion', models.CharField(blank=True, help_text='Relación con el contacto de emergencia', max_length=100, null=True)),
                ('representante_nombre', models.CharField(blank=True, help_text='Nombre del representante legal', max_length=200, null=True)),
                ('representante_identificacion', models.CharField(blank=True, help_text='Identificación del representante legal', max_length=50, null=True)),
                ('representante_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('representante_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('MOROSO', 'Moroso'), ('SUSPENDIDO', 'Suspendido'), ('VETADO', 'Vetado')], default='ACTIVO', max_length=20)),
                ('calificacion', models.IntegerField(default=5, help_text='Calificación como arrendatario (1-5 estrellas)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('historial_crediticio', models.TextField(blank=True, help_text='Notas sobre historial crediticio', null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones generales', null=True)),
                ('notas_internas', models.TextField(blank=True, help_text='Notas de uso interno', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now, help_text='Fecha de registro como arrendatario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrendatarios_creados', to=settings.AUTH_USER_MODEL)),
                ('tipo_arrendatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arrendatarios', to='arrendatarios.tipoarrendatario')),
            ],
            options={
                'verbose_name': 'Arrendatario',
                'verbose_name_plural': 'Arrendatarios',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoArrendatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CEDULA', 'Cédula de Identidad'), ('PASAPORTE', 'Pasaporte'), ('RUC', 'RUC'), ('CONSTANCIA_TRABAJO', 'Constancia de Trabajo'), ('CARTA_RECOMENDACION', 'Carta de Recomendación'), ('CERTIFICADO_BANCARIO', 'Certificado Bancario'), ('CONTRATO_ANTERIOR', 'Contrato de Arriendo Anterior'), ('OTRO', 'Otro')], max_length=30)),
                ('titulo', models.CharField(help_text='Título o descripción del documento', max_length=200)),
                ('archivo', models.FileField(help_text='Archivo del documento', upload_to='arrendatarios/documentos/%Y/%m/')),
                ('fecha_emision', models.DateField(blank=True, help_text='Fecha de emisión del documento', null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha de vencimiento del documento', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='arrendatarios.arrendatario')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_arrendatarios_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de Arrendatario',
                'verbose_name_plural': 'Documentos de Arrendatarios',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ContratoArriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(help_text='Número único del contrato', max_length=50, unique=True)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del contrato')),
                ('fecha_fin', models.DateField(help_text='Fecha de finalización del contrato')),
                ('valor_arriendo', models.DecimalField(decimal_places=2, help_text='Valor mensual del arriendo', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('valor_deposito', models.DecimalField(decimal_places=2, default=0, help_text='Valor del depósito de garantía', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('gastos_comunes', models.DecimalField(decimal_places=2, default=0, help_text='Gastos comunes mensuales', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tipo_pago', models.CharField(choices=[('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='MENSUAL', max_length=20)),
                ('dia_pago', models.IntegerField(default=5, help_text='Día del mes para realizar el pago', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('permite_incremento', models.BooleanField(default=True, help_text='¿Se permite incremento anual del arriendo?')),
                ('porcentaje_incremento', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de incremento anual', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('incluye_servicios', models.BooleanField(default=False, help_text='¿El arriendo incluye servicios básicos?')),
                ('servicios_incluidos', models.TextField(blank=True, help_text='Detalle de servicios incluidos', null=True)),
                ('permite_subarriendo', models.BooleanField(default=False, help_text='¿Se permite subarrendar?')),
                ('requiere_seguro', models.BooleanField(default=False, help_text='¿Se requiere seguro del inmueble?')),
                ('clausulas_especiales', models.TextField(blank=True, help_text='Cláusulas especiales del contrato', null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('VIGENTE', 'Vigente'), ('RENOVADO', 'Renovado'), ('FINALIZADO', 'Finalizado'), ('RESCINDIDO', 'Rescindido'), ('VENCIDO', 'Vencido')], default='BORRADOR', max_length=20)),
                ('fecha_firma', models.DateField(blank=True, help_text='Fecha de firma del contrato', null=True)),
                ('archivo_contrato', models.FileField(blank=True, help_text='Archivo PDF del contrato firmado', null=True, upload_to='contratos/%Y/%m/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='arrendatarios.arrendatario')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_creados', to=settings.AUTH_USER_MODEL)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='inmuebles.inmueble')),
            ],
            options={
                'verbose_name': 'Contrato de Arriendo',
                'verbose_name_plural': 'Contratos de Arriendo',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['numero_contrato'], name='arrendatari_numero__36ef16_idx'), models.Index(fields=['arrendatario', 'estado'], name='arrendatari_arrenda_070999_idx'), models.Index(fields=['inmueble', 'estado'], name='arrendatari_inmuebl_382100_idx'), models.Index(fields=['fecha_inicio', 'fecha_fin'], name='arrendatari_fecha_i_61e274_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='arrendatario',
            index=models.Index(fields=['codigo'], name='arrendatari_codigo_5475ef_idx'),
        ),
        migrations.AddIndex(
            model_name='arrendatario',
            index=models.Index(fields=['identificacion'], name='arrendatari_identif_7d0dc2_idx'),
        ),
        migrations.AddIndex(
            model_name='arrendatario',
            index=models.Index(fields=['estado', 'activo'], name='arrendatari_estado_e6346e_idx'),
        ),
        migrations.AddIndex(
            model_name='arrendatario',
            index=models.Index(fields=['tipo_persona'], name='arrendatari_tipo_pe_5137e6_idx'),
        ),
    ]
