# Generated by Django 5.2.7 on 2025-10-24 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='unidad_medida',
        ),
        migrations.DeleteModel(
            name='UnidadMedida',
        ),
    ]
