# Generated by Django 5.2.4 on 2025-10-28 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_producto_unidad_medida_delete_unidadmedida'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='producto',
            name='productos_p_codigo__7c1f60_idx',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='codigo_barras',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_maximo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_minimo',
        ),
    ]
