# Generated by Django 5.2.4 on 2025-10-28 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_producto_productos_p_codigo__7c1f60_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='nit',
            new_name='identificacion',
        ),
        migrations.RemoveField(
            model_name='categoriaproducto',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='loteproducto',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='creado_por',
        ),
        migrations.AlterField(
            model_name='loteproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_productos', to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_productos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_productos', to='productos.loteproducto'),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_productos_stock', to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='usuario_responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_productos_responsable', to=settings.AUTH_USER_MODEL),
        ),
    ]
