# Generated by Django 5.2.4 on 2025-10-30 03:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Cliente',
                'verbose_name_plural': 'Tipos de Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del cliente', max_length=20, unique=True)),
                ('identificacion', models.CharField(help_text='Número de identificación', max_length=50, unique=True)),
                ('razon_social', models.CharField(help_text='Razón social o nombre de la empresa', max_length=200)),
                ('nombre_comercial', models.CharField(blank=True, help_text='Nombre comercial', max_length=200, null=True)),
                ('tipo_empresa', models.CharField(choices=[('PRIVADA', 'Empresa Privada'), ('PUBLICA', 'Empresa Pública'), ('MIXTA', 'Empresa Mixta'), ('COOPERATIVA', 'Cooperativa'), ('INDIVIDUAL', 'Persona Natural'), ('ONG', 'ONG')], default='PRIVADA', max_length=20)),
                ('telefono_principal', models.CharField(max_length=20)),
                ('telefono_secundario', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('direccion', models.TextField(help_text='Dirección completa')),
                ('ciudad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('pais', models.CharField(default='Ecuador', max_length=100)),
                ('nombre_contacto', models.CharField(help_text='Nombre del contacto principal', max_length=200)),
                ('cargo_contacto', models.CharField(blank=True, help_text='Cargo del contacto', max_length=100, null=True)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('email_contacto', models.EmailField(max_length=254)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido'), ('MOROSO', 'Moroso')], default='ACTIVO', max_length=20)),
                ('calificacion', models.IntegerField(default=5, help_text='Calificación del cliente (1-5 estrellas)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('notas_internas', models.TextField(blank=True, help_text='Notas de uso interno', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_creados', to=settings.AUTH_USER_MODEL)),
                ('tipo_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='clientes.tipocliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='ContactoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('es_principal', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Contacto de Cliente',
                'verbose_name_plural': 'Contactos de Clientes',
                'ordering': ['-es_principal', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='DireccionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRINCIPAL', 'Dirección Principal'), ('ENTREGA', 'Dirección de Entrega'), ('FACTURACION', 'Dirección de Facturación'), ('OTRA', 'Otra')], default='ENTREGA', max_length=20)),
                ('nombre_referencia', models.CharField(help_text='Nombre de referencia (ej: Bodega Central, Sucursal Norte)', max_length=100)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('persona_recibe', models.CharField(blank=True, help_text='Persona que recibe en esta dirección', max_length=200, null=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Dirección de Cliente',
                'verbose_name_plural': 'Direcciones de Clientes',
                'ordering': ['-es_principal', 'nombre_referencia'],
            },
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['codigo'], name='clientes_cl_codigo_b9bbc6_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['identificacion'], name='clientes_cl_identif_add71b_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['razon_social'], name='clientes_cl_razon_s_eb90c9_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['estado', 'activo'], name='clientes_cl_estado_67dbb0_idx'),
        ),
    ]
