# Generated by Django 5.2.4 on 2025-10-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código único del cliente', max_length=20, unique=True),
        ),
    ]
